# Please make sure to update the license_key information with the
# license key for your New Relic account.
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'YOUR_LICENSE_KEY_HERE'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# Agent configuration.
#
agents:
  twilio:
    #
    # Update with your Twilio account sid and auth token:
    #
    account_sid: 'YOUR_TWILIO_ACCOUNT_SID_HERE'
    auth_token: 'YOUR_TWILIO_AUTH_TOKEN_HERE'
